2023-03-22 18:21:02,797 -  nornir.core -     INFO -        run() - Running task 'hello_world' with args {} on 5 hosts
2023-03-22 18:21:02,799 - nornir.core.task -    ERROR -      start() - Host 'CISCO-RT-1': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<input>", line 2, in hello_world
NameError: name 'Result' is not defined

2023-03-22 18:21:02,799 - nornir.core.task -    ERROR -      start() - Host 'CISCO-RT-2': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<input>", line 2, in hello_world
NameError: name 'Result' is not defined

2023-03-22 18:21:02,799 - nornir.core.task -    ERROR -      start() - Host 'CISCO-RT-5': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<input>", line 2, in hello_world
NameError: name 'Result' is not defined

2023-03-22 18:21:02,799 - nornir.core.task -    ERROR -      start() - Host 'CISCO-RT-3': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<input>", line 2, in hello_world
NameError: name 'Result' is not defined

2023-03-22 18:21:02,799 - nornir.core.task -    ERROR -      start() - Host 'CISCO-RT-4': task 'hello_world' failed with traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\site-packages\nornir\core\task.py", line 99, in start
    r = self.task(self, **self.params)
  File "<input>", line 2, in hello_world
NameError: name 'Result' is not defined

